name: Install
description: Set up Node.js and pnpm and install dependencies

inputs:
  node-version:
    description: Node.js version to install (default = 24)
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        package_json_file: package.json
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
