name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: pnpm test
