name: Test
on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: [16, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Unit tests
        run: yarn && yarn test

      - name: Installation test (npm)
        run: |
          npm install -g
          tablemark --version
          npm uninstall -g tablemark-cli

      - name: Installation test (npx)
        run: |
          npx -p . tablemark --version

      - name: Add yarn global directory to path
        if: runner.os != 'Windows'
        run: yarn global bin >> $GITHUB_PATH

      - name: Add yarn global directory to path (Windows)
        if: runner.os == 'Windows'
        run: yarn global bin >> $env:GITHUB_PATH

      - name: Installation test (yarn)
        run: |
          yarn global add $PWD
          tablemark --version
          yarn global remove tablemark-cli
