name: Test
on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: [16, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Unit tests
        run: yarn && yarn test
      - name: Installation test (npm)
        run: |
          npm install -g
          tablemark --version
          npm uninstall -g tablemark-cli
      - name: Installation test (npx)
        run: |
          npx -p $GITHUB_WORKSPACE tablemark --version
      - name: Installation test (yarn)
        run: |
          $env:Path += ";$(yarn global bin)"
          yarn global add $GITHUB_WORKSPACE
          tablemark --version
          yarn global remove tablemark
